#ifndef __DEFINE_H__
#define __DEFINE_H__

// ms
#define TEMPO_VERMELHO_VERMELHO 2000
#define TEMPO_VERDE_VERMELHO 10000
#define TEMPO_AMARELO_VERMELHO 2000
#define TEMPO_PEDESTRE 10000

typedef enum{
	
	VERMELHO_VERMELHO,
	VERDE_VERMELHO,
	AMARELO_VERMELHO,
	VERMELHO_VERMELHO1,
	VERMELHO_VERDE,
	VERMELHO_AMARELO,
	PEDESTRE
	
} SinaleiroEstados;

#define PORTF_VERMELHO 	0b10001
#define PORTF_AMARELO 	0b00001
#define PORTF_VERDE			0b10000

#define PORTN_VERMELHO	0b11
#define PORTN_AMARELO		0b01
#define	PORTN_VERDE			0b10

#endif